django_apps/django_apps/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register_user'),
    path('profile/', user_views.profile, name='profile_user'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login_user'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout_user'),
    path('', include('poll_webapp.urls')),
]

django_apps/poll_webapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (
	PollListView,
	PollDetailView,
    ResultListView
	# Poll_votesCreateView
)
from . import views

# app_name='poll_webapp'
urlpatterns = [
    path('', PollListView.as_view(), name='poll-home'),
    path('polls', PollListView.as_view(), name='poll-polls'),
    path('polls/<int:pk>/', PollDetailView.as_view(), name='poll-detail'),
    path('about', views.about, name='poll-about'),
    path('results', ResultListView.as_view(), name='poll-result'),
    url(r'^(?P<poll_id>[0-9]+)/vote/', views.vote, name='poll-vote'),
    # path('candidates', views.candidates, name='poll-candidates'),
]
    # path(r'^(?P<poll_id>[0-9]+)/vote/$', views.vote, name='poll-vote'),
    # path('vote', Poll_votesCreateView.as_view(), name='poll-vote'),

django_apps/poll_webapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import ArrayField

# POLL_OPTIONS = ()

class Poll(models.Model):

	title = models.CharField(max_length=50, default='dummy-poll')
	question_text = models.TextField(default='dummy-desc')
	date_posted = models.DateTimeField(default=timezone.now)
	# options = ArrayField(models.CharField(max_length=20, default='dummy-ans'),default=list('abc'))
	# options = models.CharField(max_length=128, default='a')
	# Poll_anss = models.ForeignKey(Poll_anss)

	"""docstring for Polls"""
	# def __init__(self, arg):
	# 	super(Polls, self).__init__()
	# 	self.arg = arg

		
class Poll_options(models.Model):
	question = models.ForeignKey(Poll, on_delete=models.CASCADE)
	option_text = models.CharField(max_length=28, default='a')
	# def __str__(self):
	# 	return self.option_text	


class Poll_votes(models.Model):

	ans_text = models.ForeignKey(Poll_options, on_delete=models.CASCADE)
	# poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
	voter = models.ForeignKey(User, on_delete=models.CASCADE)
	date_voted = models.DateTimeField(default=timezone.now)

	"""docstring for Poll_anss"""
	# def __init__(self, arg):
	# 	super(Poll_anss, self).__init__()
	# 	self.arg = arg
	
	# def get_absolute_url(self):
	# 	return reverse('poll-vote')

django_apps/users/models.py
from django.db import models

# Create your models here.

django_apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):

	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

django_apps/poll_webapp/views.py
# Views file for poll
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Poll_options,Poll,Poll_votes
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import (
    ListView,
    DetailView,
    # CreateView
)

def home(request):
    return render(request, 'poll_webapp/home.html')

def about(request):
    return render(request, 'poll_webapp/about.html', {'title': 'About'})


def result(request):
    return render(request, 'poll_webapp/results.html')


@login_required
def vote(request, poll_id):
    voted = False
    opnid = request.POST['ops']
    optn = Poll_options.objects.filter(id=opnid).first()
    user1 = request.user
    question = get_object_or_404(Poll, pk=poll_id)
    print("Question: ",question)
    print("Selected choice: ", optn)
    # print(optn.question.id==int(poll_id))    
    if (Poll_votes.objects.filter(voter=user1)):
        for vote1 in Poll_votes.objects.filter(voter=user1).all():
            print(vote1.ans_text.question.id)
            print(int(poll_id))
            print(vote1.ans_text.question.id==int(poll_id))
            if(vote1.ans_text.question.id==int(poll_id)):
                voted = True
        
        print(voted)
        print(not voted)
        if(not voted):
            print("Inner else")
            newvote = Poll_votes(ans_text=optn, voter=user1)
            newvote.save()
            messages.success(request, f'Your vote has been recorded !')
            return redirect('poll-result')
        else:
            messages.warning(request, f'You have already voted for this poll, try another!')
            return redirect('poll-home')
    else:
        print("outer else")
        newvote = Poll_votes(ans_text=optn, voter=user1)
        newvote.save()
        messages.success(request, f'Your vote has been recorded !')
        return redirect('poll-result')
        # try:
        #     selected_choice = question.poll_options_set.get(pk=request.POST['ops.id'])
        # except (KeyError, Poll_options.DoesNotExist):
        #     #display the question voting form
        #     return render(request, 'poll_webapp/polls.html', {'question': question, 'error_message':"You didn't select a choice"})
        # else:

        #     # selected_choice.votes += 1
        #     # selected_choice.save()
        #     #Always submit an HttpResponseRedirect after successfully dealing with POST data
        #     #This prevents the form being posted twice if a user hits the back button
        #     return HttpResponseRedirect(reverse('poll-about'), args=(poll_id))

    # else:



# def polls(request):
    
#     return render(request, 'poll_webapp/polls.html', context, {'title': 'Live polls'})

context = {
        'polls_obj': Poll.objects.all(),
        'poll_ops': Poll.poll_options_set,
        'pollvotes':Poll_votes.objects.all() 
    }

class PollListView(ListView):
    model = Poll
    template_name = 'poll_webapp/polls.html'
    context_object_name = 'polls_obj'
    ordering = ['-date_posted']
    paginate_by = 2


class ResultListView(ListView):
    model = Poll
    template_name = 'poll_webapp/results.html'
    context_object_name = 'polls_obj'
    ordering = ['-date_posted']

# def candidates(request):
#   cand = {
#       'cand_obj': Poll_ans.objects.all()
#   }
#   return render(request, 'poll_webapp/candidates.html', cand)

class PollDetailView(DetailView):
    model = Poll
    # context_object_name = 'poll_ops'
    # def get_context_data(self, **kwargs):
    #     # xxx will be available in the template as the related objects
    #     context = super(PollDetailView, self).get_context_data(**kwargs)
    #     context['poll_ops'] = Poll_options.objects.filter('option_text')
    #     return context



# class Poll_votesCreateView(LoginRequiredMixin, CreateView):
#     model = Poll_votes
#     template_name = 'poll_webapp/poll_detail.html'
#     # fields = ['ans_text']
#     # success_url = reverse('poll_webapp/about.html')

#     def get_initial(self):
#         initial = super().get_initial()
#         # cpf - it's the name of the field on your current form
#         # self.args will be filled from URL. I'd suggest to use named parameters
#         # so you can access e.g. self.kwargs['cpf_initial']
#         initial['ops'] = self.args[0] 
#         return initial

#     def form_valid(self, form):
#         form.instance.voter = self.request.user
#         return super().form_valid(form)

django_apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserRegisterForm
from poll_webapp.models import Poll

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account created for { username }! You can now login')
			return redirect('login-user')
	else:
		form = UserRegisterForm()
	return render(request, 'users/register.html', {'form':form})

# context = {
# 	'user_polls': Poll.P
# }

@login_required
def profile(request):
	return render(request, 'users/profile.html')

django_apps/poll_webapp/templates/poll_webapp/about.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>About page</h1>
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'poll_webapp/main.css' %}">

	{% if title %}
		<title>Poll App - {{ title }}</title>
	{% else %}
		<title>Poll App</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">The Polls App</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'poll-home' %}">Home</a>
	          <a class="nav-item nav-link" href="{% url 'poll-about' %}">About</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	        	{% if user.is_authenticated %}
	        		<a class="nav-item nav-link" href="{% url 'poll-polls' %}">Live Polls</a>
	        		<a class="nav-item nav-link" href="{% url 'poll-result' %}">Poll Results</a>
	        		<a class="nav-item nav-link" href="{% url 'profile_user' %}">{{ user.username }}</a>
	        		<a class="nav-item nav-link" href="{% url 'logout_user' %}">Logout</a>
	        	{% else %}
	        		<a class="nav-item nav-link" href="{% url 'login_user' %}">Login</a>
		            <a class="nav-item nav-link" href="{% url 'register_user' %}">Register</a>
	        	{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% if messages %}
	    	{% for message in messages %}
	    		<div class="alert alert-{{ message.tags }}">
	    			{{ message }}
	    		</div>
	    	{% endfor %}
	    	{% endif %}
	    	{% block content %}
	    	
	      	{% endblock content %}
	    </div>
	    <!-- <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div> -->
	</main>
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

django_apps/poll_webapp/templates/poll_webapp/candidates.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>New Candidates page</h1>
	{% for cand in cand_obj %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="#">Candidate-id: {{ cand.id }}</a>
		      <!-- <small class="text-muted">{{ cand.date_posted }}</small> -->
		    </div>
		    <h3><a class="article-title" href="#">{{ cand.cname }}</a></h3>
		    <p class="article-content">{{ cand.votes}}</p>
		  </div>
		</article>
	{% endfor %}
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/home.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>Poll app</h1>
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/poll_detail.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>Poll Details</h1>
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <small class="text-muted">{{ object.title }}</small>
		      <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2 class="article-title">{{ object.id }}</h2>
		    <div class="article-metadata">
		    	<form action="{% url 'poll-vote' object.id %}" method="POST">
					{% csrf_token %}
					<feildset class="form-group">
						<!-- <legend class="border-bottom mb-4">Vote form
						</legend> -->
							{% for ops in object.poll_options_set.all %}
							<input type="radio" name="ops" value="{{ ops.id }}">{{ ops.option_text }}</label><br />
						<!-- <small class="text-muted">({{ ops.id }}) {{ ops.option_text }}</small> -->
						{% endfor %}
					</feildset>
					<div class="form-group">
						<input class="btn btn-outline-info" type="submit" value="Vote!" />
					</div>
				</form>
		    </div>
		  </div>
		</article>
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/poll_votes_form.html
{% extends "poll_webapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<feildset class="form-group">
				<legend class="border-bottom mb-4">Poll-vote
				</legend>
					{{ form|crispy }}
			</feildset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Vote!</button>
			</div>
		</form>
	</div>
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/polls.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>Live Polls</h1>
	{% for poll in polls_obj %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <!-- <a class="mr-2" href="#">{{ poll.question_text }}</a> -->
		      <small class="text-muted">{{ poll.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'poll-detail' poll.id %}">{{ poll.title }}</a></h2>
		  </div>
		</article>
	{% endfor %}
	{% if is_paginated %}
		    		{% if page_obj.has_previous %}
		    			<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
		    			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		    		{% endif %}

		    		{% for num in page_obj.paginator.page_range %}
		    			{% if page_obj.number == num %}
		    				<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
		    			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
		    				<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
		    			{% endif %}
		    		{% endfor %}

		    		{% if page_obj.has_next %}
		    			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
		    			<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
		    		{% endif %}
	    		{% endif %}
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/results.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>Poll Results</h1>
		{% for poll in polls_obj %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <small class="text-muted">{{ poll.title }}</small>
		      <small class="text-muted">{{ poll.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2 class="article-title">{{ poll.question_text }}</h2>
		    <div class="article-metadata">
				{% for ops in poll.poll_options_set.all %}
				<small>Id-{{ ops.id }} Value-{{ ops.option_text }} Votes-{{ ops.poll_votes_set.count }} </small><br />
				{% endfor %}
		    </div>
		  </div>
		</article>
		{% endfor %}
{% endblock content %}

django_apps/poll_webapp/templates/poll_webapp/templates.html
<!DOCTYPE html>
<html>
<head>
	<title>Polls WebApplication</title>
</head>
<body>
	<h1>Polls homepage</h1>
</body>
</html>

django_apps/users/templates/users/login.html
{% extends "poll_webapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<feildset class="form-group">
				<legend class="border-bottom mb-4">Log in
				</legend>
					{{ form|crispy }}
			</feildset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">login</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">New user? <a class="ml-2" href="{% url 'register_user' %}">Register here!</a></small>
		</div>
	</div>
{% endblock content %}

django_apps/users/templates/users/logout.html
{% extends "poll_webapp/base.html" %}
{% block content %}
<h3>You have been logged out!</h3>
	<div class="content-section">
		<div class="border-top pt-3">
			<small class="text-muted">
				<a class="ml-2" href="{% url 'login_user' %}">Login Again</a>
			</small>
		</div>
	</div>
{% endblock content %}

django_apps/users/templates/users/profile.html
{% extends "poll_webapp/base.html" %}
{% block content %}
	<h1>Live Polls</h1>
	{% for poll in polls_obj.user_set.all %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <!-- <a class="mr-2" href="#">{{ poll.question_text }}</a> -->
		      <small class="text-muted">{{ poll.date_posted|date:"F d, Y" }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'poll-detail' poll.id %}">{{ poll.title }}</a></h2>
		  </div>
		</article>
	{% endfor %}
{% endblock content %}

django_apps/users/templates/users/register.html
{% extends "poll_webapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<feildset class="form-group">
				<legend class="border-bottom mb-4">Register now to vote!
				</legend>
					{{ form|crispy }}
			</feildset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Sign up!</button>
			</div>
		</form>
		<div class="border-top pt-3">
			<small class="text-muted">Already registerd? <a class="ml-2" href="{% url 'login_user' %}">Sign in</a></small>
		</div>
	</div>
{% endblock content %}